import copy
from typing import Any

DEFAULT_CONFIG: dict = {
    "schema_version": 1,
    "style": {
        "colors": {
            "primary": "#1e3a8a",
            "secondary": "#2563eb",
            "primary_light": "#eff6ff",
            "text_primary": "#1f2937",
            "text_body": "#374151",
            "text_muted": "#6b7280",
            "text_faint": "#9ca3af",
            "border": "#d1d5db",
            "grid": "#e5e7eb",
            "stripe": "#f8fafc",
            "positive": "#10b981",
            "warning": "#f59e0b",
            "negative": "#ef4444",
            "info": "#3b82f6",
        },
        "chart_palette": {
            "grade": {"A": "#10b981", "B": "#22c55e", "C": "#f59e0b",
                      "D": "#f97316", "F": "#ef4444"},
            "rating": {"good": "#10b981", "warning": "#f59e0b",
                       "poor": "#ef4444", "n/a": "#9ca3af"},
            "value_chain": ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],
            "severity": {"HIGH": "#ef4444", "MEDIUM": "#f59e0b", "LOW": "#10b981"},
        },
        "font": {
            "family": "DejaVu Sans",
            "excel_family": "Calibri",
        },
        "typography": {
            "scale": 1.0,
        },
        "components": {
            "border_width_scale": 1.0,
        },
        "report_css": {
            "ink": "#1f2937",
            "ink_soft": "#374151",
            "accent": "#1e3a8a",
            "line": "#d1d5db",
            "line_soft": "#e5e7eb",
            "grey_fill": "#f8fafc",
            "head": "Inter, system-ui, sans-serif",
            "explainer_layout": "A",
            "valuation_engine": "matplotlib",
            "trailer_engine": "html",
            "html_theme": "A",
            "custom_css": "",
        },
        "layout": {
            "content_axes": [0.07, 0.055, 0.86, 0.905],
            "header_height": 0.046,
            "accent_height": 0.007,
            "footer_height": 0.022,
            "title_fontsize": 11.5,
        },
    },
    "content": {
        "report_title": "BÁO CÁO ĐỊNH GIÁ DOANH NGHIỆP",
        "report_subtitle": "SME Valuation Report",
        "cover_generated_by": "Generated by 9-agent pipeline",
        "footer_prefix": "Báo cáo tạo ngày",
        "disclaimer_default": (
            "Báo cáo này được tạo bởi hệ thống AI và chỉ mang tính tham khảo. "
            "Không cấu thành lời khuyên đầu tư. Các con số và nhận định trong báo "
            "cáo có thể sai lệch so với thực tế. Người dùng chịu trách nhiệm khi "
            "ra quyết định dựa trên báo cáo này."
        ),
        "disclaimer_meta": {
            "model_label": "AI Model: Claude Opus",
            "tool_label": "Tool: ValuAI",
            "currency_label": "Đơn vị: VND",
            "scope_label": "Phạm vi: SME Việt Nam",
            "limitation_label": "Giới hạn: Chỉ dựa trên BCTC được cung cấp",
        },
        "method_notes": [
            "DCF: Discounted Cash Flow dựa trên FCFF 5 năm",
            "EV/EBITDA: So sánh bội số thị trường ngành",
            "P/E: Bội số giá / lợi nhuận",
            "P/B: Bội số giá / giá trị sổ sách",
        ],
        "trailer_brand_name": "ValuAI",
        "trailer_tagline": "Định giá doanh nghiệp thông minh",
        "trailer_preview_badge": "XEM TRƯỚC",
        "trailer_footer": "Mua báo cáo đầy đủ để xem chi tiết định giá",
        "explainer_title": "GIẢI THÍCH PHƯƠNG PHÁP ĐỊNH GIÁ",
        "explainer_subtitle": "Hướng dẫn đọc báo cáo ValuAI",
        "explainer_intro": (
            "Tài liệu này giải thích các phương pháp và chỉ số được sử dụng "
            "trong báo cáo định giá doanh nghiệp."
        ),
        "explanations": [],
    },
    "images": {
        "logo": {"file": None, "mime": None, "placements": ["cover"]},
        "items": [],
    },
    "sections": [
        {"slug": "00_cover_disclaimer", "title": "Bìa & Disclaimer", "enabled": True, "order": 0},
        {"slug": "01_executive_summary", "title": "Executive Summary", "enabled": True, "order": 1},
        {"slug": "02_investment_thesis", "title": "Luận điểm đầu tư", "enabled": True, "order": 2},
        {"slug": "03_company_overview", "title": "Tổng quan DN", "enabled": True, "order": 3},
        {"slug": "04_industry", "title": "Phân tích ngành", "enabled": True, "order": 4},
        {"slug": "05_operations", "title": "Hoạt động KD", "enabled": True, "order": 5},
        {"slug": "06_financial_statements", "title": "Bảng BCTC", "enabled": True, "order": 6},
        {"slug": "07_ratios", "title": "Tỷ số tài chính", "enabled": True, "order": 7},
        {"slug": "08_projections", "title": "Dự phóng 5 năm", "enabled": True, "order": 8},
        {"slug": "09_valuation", "title": "Định giá", "enabled": True, "order": 9},
        {"slug": "10_sensitivity", "title": "Sensitivity", "enabled": True, "order": 10},
        {"slug": "11_conclusion_appendix", "title": "Kết luận", "enabled": True, "order": 11},
    ],
    "prompts": {
        "extractor": {"preamble": ""},
        "brand_scraper": {"preamble": ""},
        "industry": {"preamble": ""},
        "business_profile": {"preamble": ""},
        "projector": {"preamble": ""},
        "valuator": {"preamble": ""},
        "thesis_writer": {"preamble": ""},
    },
}


def _deep_merge(base: dict, override: dict) -> None:
    for k, v in override.items():
        if k in base and isinstance(base[k], dict) and isinstance(v, dict):
            _deep_merge(base[k], v)
        else:
            base[k] = v


def normalize_config(raw: dict | None) -> dict:
    result = copy.deepcopy(DEFAULT_CONFIG)
    _deep_merge(result, raw or {})
    return result


def validate_config(cfg: dict) -> list[str]:
    errors = []
    scale = cfg.get("style", {}).get("typography", {}).get("scale", 1.0)
    if not (0.6 <= scale <= 1.8):
        errors.append(f"typography.scale must be between 0.6 and 1.8, got {scale}")
    bw = cfg.get("style", {}).get("components", {}).get("border_width_scale", 1.0)
    if not (0.3 <= bw <= 3.0):
        errors.append(f"components.border_width_scale must be 0.3–3.0, got {bw}")
    sections = cfg.get("sections", [])
    if sections:
        slugs = {s.get("slug") for s in sections}
        required = {"00_cover_disclaimer", "01_executive_summary"}
        missing = required - slugs
        if missing:
            errors.append(f"Missing required sections: {missing}")
    return errors
