"""Sample payload for admin preview — represents a typical SME valuation."""

SAMPLE_PAYLOAD = {
    "financials": {
        "company": {
            "name": "Công ty TNHH Mẫu Việt Nam",
            "tax_code": "0123456789",
            "address": "Hà Nội, Việt Nam",
            "industry": "Sản xuất thực phẩm",
            "report_type": "Báo cáo tài chính năm",
        },
        "period": {
            "current": {"label": "Năm 2023"},
            "previous": {"label": "Năm 2022"},
        },
        "currency": "VND",
        "unit": "triệu đồng",
        "balance_sheet": {
            "current": {
                "assets": {
                    "cash_and_equivalents": 15000,
                    "short_term_investments": 5000,
                    "short_term_receivables": 25000,
                    "inventory": 30000,
                    "other_current_assets": 3000,
                    "current_assets_total": 78000,
                    "long_term_receivables": 2000,
                    "fixed_assets": 85000,
                    "investment_properties": None,
                    "long_term_investments": 10000,
                    "other_non_current_assets": 5000,
                    "non_current_assets_total": 102000,
                    "total_assets": 180000,
                },
                "liabilities": {
                    "short_term_debt": 20000,
                    "accounts_payable": 18000,
                    "other_current_liabilities": 7000,
                    "current_liabilities_total": 45000,
                    "long_term_debt": 40000,
                    "other_non_current_liabilities": 5000,
                    "non_current_liabilities_total": 45000,
                    "total_liabilities": 90000,
                },
                "equity": {
                    "share_capital": 50000,
                    "retained_earnings": 35000,
                    "other_equity": 5000,
                    "total_equity": 90000,
                },
            },
            "previous": {
                "assets": {
                    "cash_and_equivalents": 12000,
                    "short_term_investments": 3000,
                    "short_term_receivables": 20000,
                    "inventory": 25000,
                    "other_current_assets": 2500,
                    "current_assets_total": 62500,
                    "long_term_receivables": 1500,
                    "fixed_assets": 75000,
                    "investment_properties": None,
                    "long_term_investments": 8000,
                    "other_non_current_assets": 4000,
                    "non_current_assets_total": 88500,
                    "total_assets": 151000,
                },
                "liabilities": {
                    "short_term_debt": 18000,
                    "accounts_payable": 15000,
                    "other_current_liabilities": 5000,
                    "current_liabilities_total": 38000,
                    "long_term_debt": 35000,
                    "other_non_current_liabilities": 4000,
                    "non_current_liabilities_total": 39000,
                    "total_liabilities": 77000,
                },
                "equity": {
                    "share_capital": 50000,
                    "retained_earnings": 20000,
                    "other_equity": 4000,
                    "total_equity": 74000,
                },
            },
        },
        "income_statement": {
            "current": {
                "revenue": 200000,
                "revenue_deductions": 5000,
                "net_revenue": 195000,
                "cogs": 130000,
                "gross_profit": 65000,
                "financial_income": 2000,
                "financial_expense": 5000,
                "interest_expense": 4500,
                "selling_expense": 15000,
                "admin_expense": 12000,
                "operating_profit": 35000,
                "other_income": 1000,
                "other_expense": 500,
                "profit_before_tax": 35500,
                "current_tax": 7100,
                "deferred_tax": 0,
                "net_profit_after_tax": 28400,
                "eps": 5680,
            },
            "previous": {
                "revenue": 170000,
                "revenue_deductions": 4000,
                "net_revenue": 166000,
                "cogs": 112000,
                "gross_profit": 54000,
                "financial_income": 1500,
                "financial_expense": 4500,
                "interest_expense": 4000,
                "selling_expense": 13000,
                "admin_expense": 10000,
                "operating_profit": 28000,
                "other_income": 800,
                "other_expense": 300,
                "profit_before_tax": 28500,
                "current_tax": 5700,
                "deferred_tax": 0,
                "net_profit_after_tax": 22800,
                "eps": 4560,
            },
        },
        "cash_flow": {
            "current": {
                "cf_operating": 32000,
                "cf_investing": -15000,
                "cf_financing": -5000,
                "net_cf": 12000,
                "ending_cash": 15000,
            },
            "previous": {
                "cf_operating": 25000,
                "cf_investing": -12000,
                "cf_financing": -3000,
                "net_cf": 10000,
                "ending_cash": 12000,
            },
        },
        "raw_transcription": "Sample data — not from actual BCTC",
        "notes": "",
    },
    "industry": {
        "industry_name": "Sản xuất thực phẩm",
        "industry_classification_basis": "Theo doanh thu chính",
        "industry_overview": "Ngành thực phẩm Việt Nam tăng trưởng ổn định 8-10%/năm.",
        "market_size": {
            "tam_vnd_billion": 500000,
            "sam_vnd_billion": 50000,
            "som_vnd_billion": 5000,
            "assumptions": "Ước tính theo báo cáo ngành 2023",
            "company_market_share_pct": 0.04,
        },
        "industry_cagr_5y_pct": 9.0,
        "industry_growth_drivers": ["Dân số trẻ", "Thu nhập tăng", "Đô thị hóa"],
        "industry_trends": ["Sản phẩm hữu cơ", "Bao bì thân thiện môi trường"],
        "key_competitors": [
            {"name": "Công ty A", "estimated_revenue_vnd_billion": 5000, "market_share_pct": 10, "note": ""},
            {"name": "Công ty B", "estimated_revenue_vnd_billion": 3000, "market_share_pct": 6, "note": ""},
        ],
        "competitor_comparison": [
            {
                "name": "Công ty Mẫu",
                "is_subject": True,
                "revenue_vnd_billion": 200,
                "gross_margin_pct": 33.3,
                "net_margin_pct": 14.6,
                "roe_pct": 31.6,
                "ev_ebitda_est": 8.0,
                "pe_est": 12.0,
                "market_share_pct": 0.04,
                "strengths": "Chi phí thấp, thương hiệu địa phương",
                "weaknesses": "Quy mô nhỏ, phụ thuộc nguyên liệu",
            }
        ],
        "swot": {
            "strengths": ["Lợi nhuận tốt", "Quản lý chi phí hiệu quả"],
            "weaknesses": ["Quy mô nhỏ", "Phụ thuộc nhà cung cấp"],
            "opportunities": ["Mở rộng xuất khẩu", "Sản phẩm premium"],
            "threats": ["Cạnh tranh từ tập đoàn lớn", "Chi phí nguyên liệu tăng"],
        },
        "porters_5_forces": {
            "buyer_power": {"score": 3, "description": "Người mua có nhiều lựa chọn"},
            "supplier_power": {"score": 3, "description": "Nguyên liệu nhiều nguồn cung"},
            "threat_of_substitutes": {"score": 3, "description": "Sản phẩm thay thế ở mức trung bình"},
            "threat_of_new_entrants": {"score": 2, "description": "Rào cản vừa phải"},
            "competitive_rivalry": {"score": 4, "description": "Cạnh tranh gay gắt"},
        },
        "competitive_landscape": "Phân mảnh, nhiều doanh nghiệp vừa và nhỏ.",
        "industry_risks": "Biến động giá nguyên liệu, thay đổi khẩu vị người tiêu dùng.",
        "regulatory_environment": "Quản lý ATTP chặt chẽ theo Luật ATTP 2010.",
        "barriers_to_entry": ["Vốn đầu tư máy móc", "Chứng nhận ATTP", "Thương hiệu"],
        "industry_outlook_3y": "neutral — Tăng trưởng ổn định, áp lực cạnh tranh tăng.",
    },
    "business": {
        "history_inferred": "Doanh nghiệp hoạt động trên 10 năm.",
        "ownership_summary": "Công ty gia đình sở hữu đa số.",
        "shareholders": [
            {"name": "Không xác định từ BCTC", "ownership_pct": 100, "type": "Cá nhân", "note": ""},
        ],
        "management_team": [
            {"name": "Không xác định từ BCTC", "role": "Giám đốc", "background": ""},
        ],
        "founding_milestones": [
            {"year": 2010, "event": "Thành lập công ty"},
            {"year": 2015, "event": "Mở rộng sản xuất"},
        ],
        "headcount": "50-100 nhân viên (ước tính)",
        "management": "Quản lý gia đình",
        "business_model": {
            "summary": "Sản xuất và phân phối thực phẩm cho thị trường nội địa.",
            "revenue_model": "Bán hàng trực tiếp và qua kênh phân phối",
            "products_services": "Thực phẩm chế biến",
            "customer_segments": "Hộ gia đình, siêu thị",
        },
        "revenue_breakdown": [
            {"product": "Sản phẩm chính", "pct_of_revenue": 80, "note": ""},
            {"product": "Sản phẩm phụ", "pct_of_revenue": 20, "note": ""},
        ],
        "top_customers": [
            {"name": "Không xác định từ BCTC", "revenue_pct": 0, "note": ""},
        ],
        "top_suppliers": [
            {"name": "Không xác định từ BCTC", "cost_pct": 0, "note": ""},
        ],
        "unit_economics": {
            "gross_margin_pct": 33.3,
            "operating_margin_pct": 17.9,
            "comments": "Biên lợi nhuận gộp tốt so với ngành.",
        },
        "value_chain": {
            "input": "Nguyên liệu thô từ nhà cung cấp",
            "production": "Sản xuất tại nhà máy",
            "distribution": "Phân phối qua đại lý và siêu thị",
            "customer": "Người tiêu dùng cuối cùng",
        },
        "scale_indicators": {
            "revenue_size_class": "Trung bình",
            "employee_estimate": "50-100",
            "asset_intensity": "Trung bình",
        },
        "competitive_position": "challenger",
        "growth_stage": "mature",
    },
    "ratios": {
        "liquidity": {
            "current_ratio": {"value": 1.73, "rating": "good"},
            "quick_ratio": {"value": 1.07, "rating": "good"},
            "cash_ratio": {"value": 0.33, "rating": "warning"},
        },
        "leverage": {
            "debt_ratio": {"value": 0.5, "rating": "good"},
            "debt_to_equity": {"value": 1.0, "rating": "warning"},
            "equity_multiplier": {"value": 2.0, "rating": "warning"},
            "interest_coverage": {"value": 7.78, "rating": "good"},
            "debt_to_ebitda": {"value": 1.52, "rating": "good"},
        },
        "profitability": {
            "gross_margin": {"value": 33.33, "rating": "good"},
            "operating_margin": {"value": 17.95, "rating": "good"},
            "ebitda_margin": {"value": 22.05, "rating": "good"},
            "net_margin": {"value": 14.56, "rating": "good"},
            "roa": {"value": 15.78, "rating": "good"},
            "roe": {"value": 31.56, "rating": "good"},
        },
        "efficiency": {
            "asset_turnover": {"value": 1.08, "rating": "good"},
            "inventory_turnover": {"value": 4.33, "rating": "good"},
            "receivables_turnover": {"value": 7.8, "rating": "good"},
        },
    },
    "growth": {
        "revenue_growth_pct": 17.65,
        "net_profit_growth_pct": 24.56,
        "total_assets_growth_pct": 19.21,
        "equity_growth_pct": 21.62,
    },
    "dupont": {
        "net_margin": 14.56,
        "asset_turnover": 1.08,
        "equity_multiplier": 2.0,
        "roe": 31.56,
    },
    "working_capital_days": {
        "dso": 46.79,
        "dio": 84.25,
        "dpo": 50.54,
        "ccc": 80.5,
    },
    "quality_of_earnings": {
        "net_income": 28400,
        "cf_operating": 32000,
        "accrual_ratio": -0.02,
        "assessment": "good",
        "comment": "OCF > LNST: chất lượng lợi nhuận tốt.",
    },
    "projection": {
        "base_year_label": "2023",
        "assumptions": {
            "revenue_growth_pct": [15, 13, 11, 9, 7],
            "growth_rationale": "Tăng trưởng giảm dần theo S-curve, phù hợp CAGR ngành 9%",
            "gross_margin_pct": [33.5, 33.8, 34.0, 34.0, 34.0],
            "operating_expense_pct_revenue": [14.0, 13.5, 13.0, 13.0, 13.0],
            "tax_rate_pct": 20.0,
            "depreciation_pct_revenue": [4.5, 4.3, 4.2, 4.0, 4.0],
            "capex_pct_revenue": [5.0, 4.5, 4.0, 4.0, 4.0],
            "working_capital_days": {"dso": 47, "dio": 84, "dpo": 51},
            "rationale_capex": "Đầu tư duy trì và mở rộng nhỏ",
            "rationale_wc": "Vòng quay vốn lưu động ổn định",
        },
        "projections": [
            {
                "year_index": 1, "year_label": "2024",
                "revenue": 230000, "growth_pct": 15.0,
                "cogs": 152950, "gross_profit": 77050,
                "operating_expense": 32200, "ebit": 44850,
                "depreciation": 10350, "ebitda": 55200,
                "interest_expense": 4500,
                "profit_before_tax": 40350, "tax": 8070,
                "net_income": 32280,
                "capex": 11500, "change_in_wc": 5000,
                "fcff": 38100,
                "ebitda_margin_pct": 24.0, "net_margin_pct": 14.0,
            },
            {
                "year_index": 2, "year_label": "2025",
                "revenue": 259900, "growth_pct": 13.0,
                "cogs": 172334, "gross_profit": 87566,
                "operating_expense": 35087, "ebit": 52479,
                "depreciation": 11176, "ebitda": 63655,
                "interest_expense": 4000,
                "profit_before_tax": 48479, "tax": 9696,
                "net_income": 38783,
                "capex": 11696, "change_in_wc": 4500,
                "fcff": 45959,
                "ebitda_margin_pct": 24.5, "net_margin_pct": 14.9,
            },
            {
                "year_index": 3, "year_label": "2026",
                "revenue": 288489, "growth_pct": 11.0,
                "cogs": 190403, "gross_profit": 98086,
                "operating_expense": 37504, "ebit": 60582,
                "depreciation": 12116, "ebitda": 72698,
                "interest_expense": 3500,
                "profit_before_tax": 57082, "tax": 11416,
                "net_income": 45666,
                "capex": 11540, "change_in_wc": 4200,
                "fcff": 55842,
                "ebitda_margin_pct": 25.2, "net_margin_pct": 15.8,
            },
            {
                "year_index": 4, "year_label": "2027",
                "revenue": 314453, "growth_pct": 9.0,
                "cogs": 207540, "gross_profit": 106913,
                "operating_expense": 40879, "ebit": 66034,
                "depreciation": 12578, "ebitda": 78612,
                "interest_expense": 3000,
                "profit_before_tax": 63034, "tax": 12607,
                "net_income": 50427,
                "capex": 12578, "change_in_wc": 3800,
                "fcff": 62832,
                "ebitda_margin_pct": 25.0, "net_margin_pct": 16.0,
            },
            {
                "year_index": 5, "year_label": "2028",
                "revenue": 336464, "growth_pct": 7.0,
                "cogs": 222066, "gross_profit": 114398,
                "operating_expense": 43740, "ebit": 70658,
                "depreciation": 13459, "ebitda": 84117,
                "interest_expense": 2500,
                "profit_before_tax": 68158, "tax": 13632,
                "net_income": 54526,
                "capex": 13459, "change_in_wc": 3200,
                "fcff": 66858,
                "ebitda_margin_pct": 25.0, "net_margin_pct": 16.2,
            },
        ],
        "summary_5y": {
            "revenue_cagr_pct": 10.9,
            "ebitda_cagr_pct": 11.1,
            "fcff_cumulative": 269591,
            "comments": "Tăng trưởng vững chắc, biên lợi nhuận cải thiện.",
        },
    },
    "valuation": {
        "assumptions": {
            "wacc_pct": 14.5,
            "wacc_breakdown": {
                "risk_free_rate_pct": 4.5,
                "equity_risk_premium_pct": 7.0,
                "beta": 1.1,
                "size_premium_pct": 2.0,
                "country_risk_pct": 1.5,
                "total_cost_of_equity_pct": 15.7,
                "cost_of_debt_pct": 9.0,
                "tax_shield_pct": 20.0,
                "after_tax_cost_of_debt_pct": 7.2,
                "debt_weight_pct": 50.0,
                "equity_weight_pct": 50.0,
            },
            "terminal_growth_pct": 4.0,
            "terminal_growth_rationale": "Phù hợp với tăng trưởng GDP dài hạn Việt Nam",
            "ev_ebitda_multiple": 8.0,
            "ev_ebitda_rationale": "Bội số ngành thực phẩm Đông Nam Á",
            "pe_multiple": 12.0,
            "pe_rationale": "Phù hợp với doanh nghiệp SME lợi nhuận ổn định",
            "pb_multiple": 2.5,
            "pb_rationale": "Phù hợp với tài sản cố định đáng kể",
            "minority_discount_pct": 20.0,
            "minority_discount_rationale": "Áp dụng cho cổ phần thiểu số",
        },
        "dcf": {
            "pv_fcff": 185000,
            "terminal_value": 220000,
            "pv_terminal_value": 112000,
            "enterprise_value": 297000,
            "net_debt": 45000,
            "equity_value": 252000,
        },
        "multiples": {
            "ev_ebitda": {
                "ebitda": 55200,
                "multiple": 8.0,
                "enterprise_value": 441600,
                "equity_value": 396600,
            },
            "pe": {
                "net_income": 28400,
                "multiple": 12.0,
                "equity_value": 340800,
            },
            "pb": {
                "book_value": 90000,
                "multiple": 2.5,
                "equity_value": 225000,
            },
        },
        "football_field": [
            {"method": "DCF", "low": 220000, "mid": 252000, "high": 290000},
            {"method": "EV/EBITDA", "low": 350000, "mid": 396600, "high": 450000},
            {"method": "P/E", "low": 290000, "mid": 340800, "high": 400000},
            {"method": "P/B", "low": 180000, "mid": 225000, "high": 270000},
        ],
        "sensitivity": {
            "wacc_range": [12.5, 13.0, 13.5, 14.5, 15.5],
            "g_range": [2.0, 3.0, 4.0, 5.0, 6.0],
            "matrix": [
                [320000, 340000, 360000, 400000, 440000],
                [300000, 315000, 335000, 370000, 410000],
                [280000, 295000, 310000, 340000, 380000],
                [252000, 265000, 280000, 305000, 335000],
                [230000, 242000, 255000, 278000, 305000],
            ],
        },
        "scenarios": {
            "bull": {"equity_value": 380000, "fcff_adj": "+25%", "description": "Tăng trưởng vượt kỳ vọng"},
            "base": {"equity_value": 252000, "fcff_adj": "Base", "description": "Kịch bản cơ sở"},
            "bear": {"equity_value": 176000, "fcff_adj": "-30%", "description": "Suy giảm thị trường"},
        },
        "summary": {
            "fair_value_low": 220000,
            "fair_value_mid": 278000,
            "fair_value_high": 340000,
            "minority_discount_pct": 20.0,
            "fair_value_minority_low": 176000,
            "fair_value_minority_mid": 222400,
            "fair_value_minority_high": 272000,
        },
        "waterfall": {
            "enterprise_value": 297000,
            "less_debt": -60000,
            "plus_cash": 15000,
            "equity_value": 252000,
        },
    },
    "thesis": {
        "report_version": "1.0",
        "report_date": "2024-01-01",
        "disclaimer": "Chỉ mang tính tham khảo.",
        "executive_summary": {
            "headline": "Công ty có nền tảng tài chính vững chắc, định giá hợp lý",
            "company_brief": "SME sản xuất thực phẩm hoạt động trên 10 năm",
            "industry_brief": "Ngành thực phẩm tăng trưởng 9%/năm",
            "scale_brief": "Doanh thu 200 tỷ, tổng tài sản 180 tỷ",
            "valuation_result": "Fair value: 220-340 tỷ VND",
            "recommendation": "BUY — định giá hấp dẫn, tiềm năng tăng trưởng tốt",
            "key_drivers": ["Lợi nhuận cao", "Quản lý vốn tốt", "Thị trường tăng trưởng"],
        },
        "investment_case_summary": "Doanh nghiệp có lợi nhuận bền vững và khả năng mở rộng.",
        "key_value_drivers_ranked": [
            {"rank": 1, "driver": "Biên lợi nhuận gộp 33%", "rationale": "Cao hơn trung bình ngành"},
            {"rank": 2, "driver": "Tăng trưởng doanh thu 18%", "rationale": "Vượt CAGR ngành"},
            {"rank": 3, "driver": "ROE 31.6%", "rationale": "Hiệu quả sử dụng vốn xuất sắc"},
        ],
        "investment_thesis": {
            "thesis_points": [
                {
                    "title": "Vị thế cạnh tranh mạnh",
                    "thesis": "Doanh nghiệp có thương hiệu tốt trong phân khúc địa phương",
                    "evidence": "Doanh thu tăng 18% dù thị trường cạnh tranh",
                },
            ],
            "catalysts": [
                {"type": "Tăng trưởng", "description": "Mở rộng kênh phân phối", "horizon": "12 tháng"},
            ],
            "risks": [
                {
                    "type": "Nguyên liệu",
                    "description": "Giá nguyên liệu biến động",
                    "severity": "MEDIUM",
                    "mitigation": "Đa dạng hóa nhà cung cấp",
                    "quantified_impact": "±2% biên lợi nhuận",
                },
            ],
        },
        "risk_matrix": [
            {"risk": "Giá nguyên liệu", "probability": 2, "impact": 2, "score": 4, "mitigation": "Hợp đồng dài hạn"},
        ],
        "operations_analysis": {
            "revenue_drivers": "Tăng sản lượng và mở rộng địa lý",
            "margin_analysis": "Biên cải thiện nhờ tối ưu chi phí",
            "channel_breakdown": "70% siêu thị, 30% trực tiếp",
            "key_metrics_observations": "CCC 80 ngày, trong ngưỡng ngành",
        },
        "financial_analysis_commentary": {
            "balance_sheet_health": "Cấu trúc vốn cân bằng, D/E = 1x",
            "income_statement_quality": "Doanh thu và lợi nhuận tăng đều",
            "cash_flow_quality": "OCF > LNST: chất lượng lợi nhuận cao",
            "leverage_view": "Đòn bẩy vừa phải, interest coverage 7.8x",
        },
        "valuation_commentary": {
            "method_comparison": "DCF thấp hơn Multiples do WACC cao",
            "reconciliation": "Trung bình có trọng số: 278 tỷ",
            "fair_value_view": "220-340 tỷ là khoảng hợp lý",
            "weighting_applied": "DCF 40%, EV/EBITDA 30%, P/E 20%, P/B 10%",
            "key_sensitivities": "WACC và terminal growth rate",
        },
        "deal_recommendation": {
            "primary_objective": "Đầu tư tăng trưởng",
            "fair_value_range_text": "220-340 tỷ VND",
            "entry_price_recommendation": "Mua dưới 280 tỷ",
            "deal_structure": "Mua cổ phần thiểu số 20-30%",
            "post_deal_governance": "Tham gia HĐQT, quyền phủ quyết chiến lược",
            "next_steps": "Due diligence trong 30 ngày",
            "pre_money_valuation": 278000,
            "investment_amount_suggested": 60000,
            "post_money_valuation": 338000,
        },
        "use_of_proceeds": [
            {"category": "Mở rộng sản xuất", "pct": 50, "amount_vnd_billion": 30, "note": ""},
            {"category": "Vốn lưu động", "pct": 30, "amount_vnd_billion": 18, "note": ""},
            {"category": "Marketing & phân phối", "pct": 20, "amount_vnd_billion": 12, "note": ""},
        ],
        "dilution_table": [
            {"shareholder": "Cổ đông hiện hữu", "pre_deal_pct": 100, "post_deal_pct": 75, "shares_note": ""},
            {"shareholder": "Nhà đầu tư mới", "pre_deal_pct": 0, "post_deal_pct": 25, "shares_note": ""},
        ],
        "exit_strategy": {
            "primary_exit": "IPO hoặc M&A chiến lược",
            "target_timeline_years": 5,
            "target_ev_at_exit": 500000,
            "exit_multiple_assumption": 10.0,
            "description": "Exit qua IPO khi doanh thu đạt 500 tỷ",
        },
        "return_scenarios": [
            {
                "scenario": "Bull",
                "irr_pct": 32,
                "moic": 3.2,
                "horizon_years": 5,
                "entry_ev": 278000,
                "exit_ev": 600000,
                "description": "Tăng trưởng vượt kỳ vọng, IPO thành công",
            },
            {
                "scenario": "Base",
                "irr_pct": 20,
                "moic": 2.1,
                "horizon_years": 5,
                "entry_ev": 278000,
                "exit_ev": 450000,
                "description": "Kịch bản trung tính",
            },
            {
                "scenario": "Bear",
                "irr_pct": 8,
                "moic": 1.4,
                "horizon_years": 5,
                "entry_ev": 278000,
                "exit_ev": 310000,
                "description": "Thị trường suy giảm, tăng trưởng chậm",
            },
        ],
    },
    "brand": {
        "primary": "#1e3a8a",
        "secondary": "#2563eb",
        "primary_light": "#eff6ff",
        "accent": "#10b981",
        "logo_b64": None,
        "logo_mime": None,
        "source": "default",
    },
}
